version: '3.8'

services:
  # ChromaDB Vector Database for Knowledge Storage
  chromadb:
    image: chromadb/chroma:latest
    container_name: solidworks-mcp-chromadb
    ports:
      - "8057:8000"  # Using port 8057 to avoid conflicts
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
      - ALLOW_RESET=TRUE
    networks:
      - solidworks-mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # SolidWorks MCP Server
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.11
    container_name: solidworks-mcp-server
    depends_on:
      chromadb:
        condition: service_healthy
    ports:
      - "5858:5858"  # MCP stdio port for Claude Desktop
    volumes:
      # Source code (for development with hot reload)
      - ./mcp_server_solidworks:/app/mcp_server_solidworks
      - ./examples:/app/examples
      - ./scripts:/app/scripts
      
      # Data and logs
      - ./data:/app/data
      - ./logs:/app/logs
      
      # C# Adapters and references
      - ./mcp_server_solidworks/solidworks_adapters:/app/mcp_server_solidworks/solidworks_adapters
      
      # Windows host mounts for SolidWorks access
      # Note: Update these paths based on your system
      - type: bind
        source: ${SOLIDWORKS_MODELS_PATH:-C:/SolidWorks/Models}
        target: /solidworks/models
      - type: bind
        source: ${SOLIDWORKS_MACROS_PATH:-C:/SolidWorks/Macros}
        target: /solidworks/macros
      - type: bind
        source: ${SOLIDWORKS_TEMPLATES_PATH:-C:/SolidWorks/Templates}
        target: /solidworks/templates
        
    environment:
      # ChromaDB Configuration
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - CHROMA_PERSIST_DIRECTORY=/app/chroma_db
      
      # MCP Server Configuration
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      
      # SolidWorks Configuration
      - SOLIDWORKS_PATH=${SOLIDWORKS_PATH:-C:/Program Files/SOLIDWORKS Corp/SOLIDWORKS}
      - SOLIDWORKS_VERSION=${SOLIDWORKS_VERSION:-2024}
      
      # Feature Flags
      - ENABLE_CHROMADB=${ENABLE_CHROMADB:-true}
      - ENABLE_EVENT_CAPTURE=${ENABLE_EVENT_CAPTURE:-true}
      - ENABLE_PERFORMANCE_METRICS=${ENABLE_PERFORMANCE_METRICS:-true}
      - ENABLE_AUTO_SAVE=${ENABLE_AUTO_SAVE:-false}
      - SANDBOX_VBA_EXECUTION=${SANDBOX_VBA_EXECUTION:-true}
      
      # Development Mode
      - RELOAD_ON_CHANGE=${RELOAD_ON_CHANGE:-true}
      - DEBUG=${DEBUG:-false}
      
    networks:
      - solidworks-mcp-network
    stdin_open: true
    tty: true
    command: ["python", "-m", "mcp_server_solidworks.mcp_host.server"]
    restart: unless-stopped

  # Development Tools Container
  dev-tools:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: solidworks-mcp-devtools
    profiles: ["dev"]  # Only runs when explicitly requested
    depends_on:
      - chromadb
    volumes:
      - ./:/app
      - solidworks_mcp_pip_cache:/root/.cache/pip
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    networks:
      - solidworks-mcp-network
    command: ["tail", "-f", "/dev/null"]  # Keep container running

  # Jupyter Notebook for Interactive Development
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: solidworks-mcp-jupyter
    profiles: ["jupyter"]  # Only runs when explicitly requested
    ports:
      - "8888:8888"
    depends_on:
      - chromadb
    volumes:
      - ./:/app
      - ./notebooks:/app/notebooks
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - solidworks-mcp-network
    command: >
      jupyter lab 
      --ip=0.0.0.0 
      --port=8888 
      --no-browser 
      --allow-root 
      --NotebookApp.token='' 
      --NotebookApp.password=''

networks:
  solidworks-mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  chroma_data:
    driver: local
  solidworks_mcp_pip_cache:
    driver: local